//
//  XCTestCase+IO.swift
//  XCTestIOKit
//
//  Created by 김호성 on 2026.01.02.
//

import XCTest

extension XCTestCase {
    
    /// Asserts that a given block of code produces the expected output for a given input.
    ///
    /// This function simulates standard input (stdin), captures the standard output (stdout)
    /// generated by the `target` closure, and performs an equality check using `XCTAssertEqual`.
    ///
    /// ### Usage Example
    /// ```swift
    /// func testGreeting() {
    ///     assertIO(input: "Swift", expected: "Hello, Swift!") {
    ///         let name = readLine() ?? ""
    ///         print("Hello, \(name)!")
    ///     }
    /// }
    /// ```
    ///
    /// - Parameters:
    ///   - input: The string to be injected into the standard input stream.
    ///   - expected: The expected string to be compared against the captured output.
    ///   - target: A closure containing the code under test that reads from input and writes to output.
    public func assertIO(input: String, expected: String, target: () -> Void) {
        let output: String? = runWithIO(input: input, block: target)
        XCTAssertEqual(output, expected)
    }
    
    /// Executes a block of code while redirecting standard input and standard output.
    /// - Parameters:
    ///   - input: A string to be written to standard input.
    ///   - block: A closure to execute while I/O is redirected.
    /// - Returns: The captured standard output as a string.
    internal func runWithIO(input: String, block: () -> Void) -> String? {
        let outputPipe = Pipe()
        let inputPipe = Pipe()
        
        let oldStdout = dup(STDOUT_FILENO)
        let oldStdin = dup(STDIN_FILENO)
        
        defer {
            fflush(stdout)
            dup2(oldStdout, STDOUT_FILENO)
            dup2(oldStdin, STDIN_FILENO)
            close(oldStdout)
            close(oldStdin)
        }
        
        dup2(outputPipe.fileHandleForWriting.fileDescriptor, STDOUT_FILENO)
        dup2(inputPipe.fileHandleForReading.fileDescriptor, STDIN_FILENO)
        
        if let inputData = input.data(using: .utf8) {
            inputPipe.fileHandleForWriting.write(inputData)
            inputPipe.fileHandleForWriting.closeFile()
        }
        
        block()
        
        fflush(stdout)
        outputPipe.fileHandleForWriting.closeFile()
        
        dup2(oldStdout, STDOUT_FILENO)
        dup2(oldStdin, STDIN_FILENO)
        
        let outputData = outputPipe.fileHandleForReading.readDataToEndOfFile()
        let outputString = String(data: outputData, encoding: .utf8)?.trimmingCharacters(in: .whitespacesAndNewlines)
        
        return outputString
    }
}
