//
//  XCTestCase+IO.swift
//  XCTestIOKit
//
//  Created by 김호성 on 2026.01.02.
//

import XCTest

@available(iOS 18.0, macOS 15.0, *)
extension XCTestCase {
    
    /// Asserts that a given block of code produces the expected output for a given input.
    ///
    /// This function simulates standard input (stdin), captures the standard output (stdout)
    /// generated by the `target` closure, and performs an equality check using `XCTAssertEqual`.
    ///
    /// ### Usage Example
    /// ```swift
    /// func testGreeting() {
    ///     assertIO(input: "Swift", expected: "Hello, Swift!") {
    ///         let name = readLine() ?? ""
    ///         print("Hello, \(name)!")
    ///     }
    /// }
    /// ```
    ///
    /// - Parameters:
    ///   - input: The string to be injected into the standard input stream.
    ///   - expected: The expected string to be compared against the captured output.
    ///   - target: A closure containing the code under test that reads from input and writes to output.
    public func assertIO(input: String, expected: String, target: () -> Void, timeLimit: Duration? = nil, memoryLimit: Memory? = nil, file: StaticString = #filePath, line: UInt = #line) {
        let (actual, time, memory) = runWithIO(input: input, block: target)
        
        if let timeLimit, time > timeLimit.attoseconds {
            XCTFail("Time Limit Exceeded: \(time) > \(timeLimit.attoseconds)", file: file, line: line)
        }
        if let memoryLimit, memory > memoryLimit.bytes {
            XCTFail("Memory Limit Exceeded: \(memory) > \(memoryLimit.bytes)", file: file, line: line)
        }
        
        XCTAssertEqual(
            actual,
            expected,
            """
            Wrong Answer
            Expected:
            \(expected)

            Actual:
            \(actual ?? "")
            """,
            file: file,
            line: line
        )
    }
    
    /// Executes a block of code while redirecting standard input and standard output.
    ///
    /// - Parameters:
    ///   - input: A string to be written to standard input.
    ///   - block: A closure to execute while I/O is redirected.
    ///
    /// - Returns: The captured standard output as a string.
    private func runWithIO(input: String, block: () -> Void) -> (output: String?, time: Int128, memory: mach_vm_size_t) {
        let outputPipe = Pipe()
        let inputPipe = Pipe()
        
        let oldStdout = dup(STDOUT_FILENO)
        let oldStdin = dup(STDIN_FILENO)
        
        defer {
            fflush(stdout)
            dup2(oldStdout, STDOUT_FILENO)
            dup2(oldStdin, STDIN_FILENO)
            close(oldStdout)
            close(oldStdin)
        }
        
        dup2(outputPipe.fileHandleForWriting.fileDescriptor, STDOUT_FILENO)
        dup2(inputPipe.fileHandleForReading.fileDescriptor, STDIN_FILENO)
        
        if let inputData = input.data(using: .utf8) {
            inputPipe.fileHandleForWriting.write(inputData)
            inputPipe.fileHandleForWriting.closeFile()
        }
        
        let (time, memory) = runWithProfiling(block)
        
        fflush(stdout)
        outputPipe.fileHandleForWriting.closeFile()
        
        dup2(oldStdout, STDOUT_FILENO)
        dup2(oldStdin, STDIN_FILENO)
        
        let outputData = outputPipe.fileHandleForReading.readDataToEndOfFile()
        let outputString = String(data: outputData, encoding: .utf8)?.trimmingCharacters(in: .whitespacesAndNewlines)
        
        return (outputString, time, memory)
    }
    
    private func peakResidentSize() -> mach_vm_size_t? {
        var info = mach_task_basic_info()
        var count = mach_msg_type_number_t(MemoryLayout<mach_task_basic_info>.size) / 4
        
        let kerr: kern_return_t = withUnsafeMutablePointer(to: &info) {
            $0.withMemoryRebound(to: integer_t.self, capacity: Int(count)) {
                task_info(
                    mach_task_self_,
                    task_flavor_t(MACH_TASK_BASIC_INFO),
                    $0,
                    &count
                )
            }
        }
        
        return kerr == KERN_SUCCESS ? info.resident_size_max : nil
    }
    
    private func runWithProfiling(_ block: () -> Void) -> (time: Int128, memory: mach_vm_size_t) {
        let clock = ContinuousClock()
        
        let time = clock.measure(block).attoseconds
        let memory = peakResidentSize() ?? 0
        
        return (time, memory)
    }
}
